# config.yaml

#TO DO!
# this needs to be checked for confirmation that it's correct, some stuff isn't right currently
#need to make sure the jump threshold pixels value is correct for the BumbleBox by default! Not the new rig (as of 2024)
#Contact distance config - is this even integrated into the code??? I don't think so currently, I THINK it's just based on pixel contact distance - CHECK!
#Add angular velocity metric, with the caveat that you haven't tested it for bugs yet - needs to be tested before integrating it, obviously
#Add something like "are bees facing each other" function to behavioral metrics, and add that to the behavioral function list here
#Need to add delete duplicate function and at least make note of it here

# BumbleBox ID and system
colony_number: "01"

# Recording options
recording_options:
  tag_tracking: true
  tag_tracking_frequency: 5
  recording_time: 20
  recording_frequency: 30
  track_recorded_videos: true
  use_parallel_ram_tracking: true
  infrared_recording: true

# Camera settings
camera_settings:
  width: 4056
  height: 3040
  frames_per_second: 5
  actual_frames_per_second: 4.4
  shutter_speed: 2500
  tuning_file: "imx477_noir.json"
  noise_reduction_mode: "Auto"
  recording_digital_zoom: null
  codec: "mp4"
  quality: 95

# ArUco tracking
tag_dictionary: "4X4_50"
box_type: "custom"

# If box type: "null", then the following custom parameters can be set manually by the user
#Use the tracking optimization script to find the best combination of parameters
aruco_params:
  minMarkerPerimeterRate: 0.02
  adaptiveThreshWinSizeMin: 3
  adaptiveThreshWinSizeMax: 31
  adaptiveThreshWinSizeStep: 3
  polygonalApproxAccuracyRate: 0.08

#data cleaning module
#need to make sure the jump threshold pixels value is correct for the BumbleBox by default! Not the new rig (as of 2024)
#Fyi, the module removes frame-level duplicate tag readings by default
date cleaning:
  #drop_unresolvable refers to duplicate tags, where we cant figure out which one is more likely to be the correct tag, so we drop them both if set to true
  #otherwise, both are flagged as being "unresolvable" but are kept in the dataframe so we know roughly how many unresolved duplicates there are
  drop_unresolvable: true
  remove_jumps: true
  jump_threshold_pixels: 500
  interpolate_data: true
  #maximum number of seconds to interpolate data between two tag reads - if max_seconds_gap is set to 3 seconds, if tag 0 is read in a frame and then only read again
  #in another frame 4 seconds later, the BumbleBox software won't interpolate between those two tag reads
  #the software uses the max_seconds_gap value and the framerate of the video to determine the threshold number of frames 
  max_seconds_gap: 3
  compute_heading_angle: true
  


# Behavior metrics
calculate_behavior_metrics: true
behavior_metrics:
  - speed
  - activity
  - distance from center
  - pairwise distance
  - contacts
  - video averages
#Contact distance - is this even integrated into the code??? I don't think so currently, I THINK it's just based on pixel contact distance - CHECK!
contact_distance: 2.0
pixel_contact_distance: 206.1
moving_threshold: 3.16

# Output
# I don't think we need these variables, need to check
#output_filename: "session_001"
#todays_folder_path: "/mnt/bumblebox/data"

# Preview settings
preview_time: 120
preview_width: 3000
preview_height: 2250
infrared_preview: true
preview_tuning_file: "imx477_noir.json"
preview_window: "QTGL"
preview_digital_zoom: [275, 0, 3300, 3040]

# Composite nest image settings
create_composite_nest_images: true
number_of_images: 60
composite_images_per_day: 1
